name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Generate .icns icon
      run: |
        if [ -f "gestor-calificaciones.png" ]; then
          ICONSET_DIR="GestorCalificacionesAules.iconset"
          mkdir -p "$ICONSET_DIR"
          
          for size in 16 32 64 128 256 512; do
            sips -z "$size" "$size" "gestor-calificaciones.png" --out "$ICONSET_DIR/icon_${size}x${size}.png"
            sips -z $((size*2)) $((size*2)) "gestor-calificaciones.png" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png"
          done
          
          iconutil -c icns "$ICONSET_DIR" -o "GestorCalificacionesAules.icns"
        fi
    
    - name: Build with PyInstaller
      run: |
        PYI_ARGS=(
          --name "GestorCalificacionesAules"
          --onefile
          --console
          --osx-bundle-identifier "com.aules.GestorCalificacionesAules"
        )
        
        if [ -f "GestorCalificacionesAules.icns" ]; then
          PYI_ARGS+=(--icon "GestorCalificacionesAules.icns")
        fi
        
        pyinstaller "${PYI_ARGS[@]}" "calificaciones_aules.py"
    
    - name: Create DMG
      run: |
        hdiutil create -volname "GestorCalificacionesAules" \
          -srcfolder "dist/GestorCalificacionesAules.app" \
          -ov -format UDZO "dist/GestorCalificacionesAules.dmg"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: |
          dist/GestorCalificacionesAules.app
          dist/GestorCalificacionesAules.dmg
