name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        Write-Host "Building executable with PyInstaller..."
        
        # Check for icon
        if (Test-Path "gestor-calificaciones.ico") {
          Write-Host "Icon found: gestor-calificaciones.ico"
          pyinstaller --onefile --console --name "Gestor_Calificaciones_Aules" --icon "gestor-calificaciones.ico" --hidden-import=bs4 --hidden-import=tqdm --hidden-import=requests --hidden-import=urllib.parse --hidden-import=json --hidden-import=re --hidden-import=time --hidden-import=os --hidden-import=sys --hidden-import=argparse --hidden-import=pydoc calificaciones_aules.py
        } else {
          Write-Host "No icon found, building without icon"
          pyinstaller --onefile --console --name "Gestor_Calificaciones_Aules" --hidden-import=bs4 --hidden-import=tqdm --hidden-import=requests --hidden-import=urllib.parse --hidden-import=json --hidden-import=re --hidden-import=time --hidden-import=os --hidden-import=sys --hidden-import=argparse --hidden-import=pydoc calificaciones_aules.py
        }
        
        Write-Host "Build completed"
        if (Test-Path "dist/Gestor_Calificaciones_Aules.exe") {
          Write-Host "OK Executable created successfully"
        } else {
          Write-Host "X Executable not found"
          exit 1
        }
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: |
          dist/Gestor_Calificaciones_Aules.exe
